export const HEALTH_TIPS = [
  "🥗 Eat a light dinner for better sleep.",
  "💧 Drink a glass of water right after waking up.",
  "🛏️ Stretch for 5 minutes before going to bed.",
  "🚶‍♂️ Take a 10-minute walk after each meal.",
  "🌞 Get at least 10 minutes of sunlight every day.",
  "📱 Avoid screens 30 minutes before bed.",
  "🥦 Add a green veggie to every meal today.",
  "😴 Aim for 7–8 hours of sleep tonight.",
  "🍎 Snack on fruit instead of chips today.",
  "💨 Practice deep breathing for 2 minutes to reduce stress.",
  "🚰 Drink at least 8 glasses of water today.",
  "🧘 Try a 5-minute mindfulness session this afternoon.",
  "💪 Add 10 squats to your daily routine.",
  "📖 Read instead of scrolling social media before bed.",
  "🥜 Choose nuts instead of sweets for your snack today.",
  "🌙 Don’t eat 2 hours before bedtime.",
  "🧴 Apply sunscreen even if you’re indoors!",
  "🪑 Sit up straight—good posture helps digestion and breathing.",
  "🧊 Cut back on sugary drinks today.",
  "🥚 Add a source of protein to your breakfast.",
  "🦶 Walk barefoot on grass for 5 minutes—it’s grounding!",
  "🧂 Skip extra salt today—your heart will thank you.",
  "🧃 Replace one soda with lemon water today.",
  "🧼 Wash your hands before every meal—even snacks.",
  "🧘‍♂️ Try child’s pose to relax your back.",
  "😄 Smile more—it boosts mood and lowers stress hormones.",
  "🏃 Do one 20-second burst of cardio after sitting for too long.",
  "🔕 Turn off all phone notifications for 1 hour today.",
  "🛑 Stop eating when 80% full—your body needs time to feel full.",
  "🥒 Include something raw (like salad) in lunch today.",
  "🧠 Do a brain game or puzzle instead of binge-watching.",
  "🫁 Breathe in deeply for 4 seconds, hold for 4, exhale for 4.",
  "🪥 Brush and floss—gum health impacts your heart too.",
  "🍲 Try a warm soup instead of heavy fast food today.",
  "🚿 Take a cold shower for 30 seconds to boost energy.",
  "📆 Plan your meals—less stress, better choices!",
  "🥤 Keep a water bottle near you all day.",
  "📵 One hour of no-screen time daily clears the mind.",
  "🛌 Create a relaxing bedtime ritual tonight.",
  "🧘 Meditate for 3 minutes today—even just sitting quietly helps.",
  "🌾 Eat whole grains instead of refined today.",
  "🍫 Dark chocolate is better than milk chocolate (just a little!).",
  "🧄 Add garlic or turmeric to your meal for immunity.",
  "🧃 Fresh juice > packaged drinks—always!",
  "🚶‍♀️ Take stairs instead of elevator once today.",
  "👣 Massage your feet at night to relax muscles.",
  "💡 Dim lights 30 minutes before bed to help melatonin.",
  "🤸 Stretch after waking up—it energizes your whole day.",
  "🧘 Sit silently with your thoughts for 2 minutes today.",
  "🍋 Add lemon to your water to improve digestion.",
];
